name: 'automation'
description: 'Automate the CI workflow with Projects'
author: 'Luca Joos'
inputs:
  token:
    required: true
    description: 'input description here'
  project:
    required: true
    description: 'Project id'
  type:
    required: true
    description: 'Type of action to perform'
  owner:
    required: false
    description: 'Owner'
  repo:
    required: false
    description: 'Repo'
  ref:
    required: false
    description: 'Ref'
  author:
    required: false
    description: 'PR author regex'
    default: .*
  title:
    required: false
    description: 'PR title regex'
    default: \[#[0-9]+\]
  match:
    required: false
    description: 'PR title match regex'
    default: '[0-9]+'
runs:
  using: 'node16'
  main: 'dist/index.js'
