name: 'pull-request-issue-automation'
description: 'Automate the Creation of Pull Requests by Referencing Issues in Title'
author: 'Luca Joos'
branding:
  icon: box
  color: gray-dark
inputs:
  token:
    required: true
    description: 'GitHub Access Token'
  owner:
    required: false
    description: 'Repository Owner'
  repo:
    required: false
    description: 'Repository'
  ref:
    required: false
    description: 'Ref of Current Pull Request'
  author:
    required: false
    description: 'Regular Expression to Match Author of Pull Request'
    default: .*
  title:
    required: false
    description: 'Regular Expression to Match Title of Pull Request'
    default: \[#[0-9]+\]
  match:
    required: false
    description: 'Regular Expression to Extract Issue from Title'
    default: '[0-9]+'
runs:
  using: 'node16'
  main: 'dist/index.js'
